spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phone_door?   useUnicode=true&characterEncoding=utf8
    username: root
    password: Mapanwei0116
    driver-class-name: com.mysql.jdbc.Driver